apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-svc2
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - port: 9090
      targetPort: 8080