apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
    matchExpressions:
      - key: tier
        operator: In
        values: [backend]
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.9.1
          ports:
            - containerPort:  80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    'app': 'nginx'
