apiVersion: v1
kind: Pod
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  containers: 
    - name: api-server
      image: lrakai/microservices:server-v1
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_URL
          # <service_name>_SERVICE_HOST:<serive_name>_SERVICE_PORT
          value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  selector:
    app: api-server
  ports:
  - port: 8080
    name: api-server
  type: ClusterIP