apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
    - name: hello-container
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-load-balance
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - port: 8080