apiVersion: v1
kind: Pod
metadata:
  name: color-app
  labels:
    app: color-app
spec:
  containers:
    - name: color-app
      image: anandnevase/color-app
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config
          mountPath: /data
      envFrom:
        - configMapRef:
            name: color-config-map
  volumes:
    - name: config
      configMap:
        name: color-config-map-dir
        # items:
        #     - key: testfile.txt
        #       path: testfile.txt